---
- name: Configurar servidores
  hosts: servidores
  become: yes
  tasks:
    - name: Actualizar cache de software
      apt:
        update_cache: yes

    - name: Actualizar el sistema
      apt:
        upgrade: dist
        autoremove: yes

    - name: Instalar apache
      apt:
        name: apache2
        state: present

    - name: Instalar cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear archivo
      file:
        path: /home/vagrant/archivo.txt
        state: touch

    - name: Copiar archivo
      copy:
        content: "Contenido del archivo\n"
        dest: /home/vagrant/archivo.txt

    - name: Crear carpeta
      file:
        path: /home/vagrant/carpeta
        state: directory

    - name: Iniciar servicio apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Agregar usuario
      user:
        name: nuevo_usuario
        state: present

    - name: Copiar script al servidor
      copy:
        src: /mnt/c/Users/DELL/mi_proyecto_ansible/script.sh
        dest: /home/vagrant/script.sh
        mode: '0755'

    - name: Ejecutar script
      shell: /home/vagrant/script.sh
